# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_rhv,multi_platform_ol
# reboot = false
# strategy = configure
# complexity = low
# disruption = medium

{{%- set pam_file="/etc/pam.d/password-auth" %}}

{{{ ansible_instantiate_variables("var_password_hashing_algorithm_pam") }}}
{{{ ansible_ensure_pam_module_configuration(pam_file, 'password', 'sufficient', 'pam_unix.so', '{{ var_password_hashing_algorithm_pam }}', '', '') }}}

- name: '{{{ rule_title }}} - Check if {{{ pam_file }}} file is present'
  ansible.builtin.stat:
    path: {{{ pam_file }}}
  register: result_pam_file_present

- name: '{{{ rule_title }}} - Check the proper remediation for the system'
  block:
    {{{ ansible_ensure_pam_facts_and_authselect_profile(pam_file) | indent(4) }}}

    - name: '{{{ rule_title }}} - Ensure the only the correct hashing algorithm option for pam_unix.so is used in {{{ pam_file }}}'
      ansible.builtin.replace:
        dest: "{{ pam_file_path }}"
        regexp: (.*password.*pam_unix\.so.*)\b{{ item }}\b=?[0-9a-zA-Z]*(.*)
        replace: '\1\2'
      when:
        item != var_password_hashing_algorithm_pam
      loop:
        - 'sha512'
        - 'yescrypt'
        - 'gost_yescrypt'
        - 'blowfish'
        - 'sha256'
        - 'md5'
        - 'bigcrypt'
      register: result_pam_hashing_options_removal

    {{{ ansible_apply_authselect_changes() | indent(4) }}}
      when:
        - result_authselect_present.stat.exists
        - result_pam_hashing_options_removal is changed
  when:
    - result_pam_file_present.stat.exists
